
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Admin
 */
public class Coin_OperatedMachine extends javax.swing.JFrame {

    /**
     * Creates new form Coin_OperatedMachine
     */
    public Coin_OperatedMachine() {
        initComponents();
        getFreeBtn.setVisible(false);
    }
    // initalize values
    int cokePrice = 10000;
    int pepsiPrice = 10000;
    int sodaPrice = 20000;
    int totalPrice = 0;
    
    int countCoke = 0;
    int countPepsi = 0;
    int countSoda = 0;
    
    int totalWin = 0;
    
    boolean freeSoda = true;
    
    boolean getFree = false; // this variable to check if the user has received the free product and set the price again
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cokeRB = new javax.swing.JRadioButton();
        pepsiRB = new javax.swing.JRadioButton();
        sodaRB = new javax.swing.JRadioButton();
        txtCokeQuantity = new javax.swing.JTextField();
        txtPepsiQuantity = new javax.swing.JTextField();
        txtSodaQuantity = new javax.swing.JTextField();
        coke_IncreaseBtn = new javax.swing.JButton();
        coke_DecreaseBtn = new javax.swing.JButton();
        pepsi_IncreaseBtn = new javax.swing.JButton();
        pepsi_DecreaseBtn = new javax.swing.JButton();
        soda_IncreaseBtn = new javax.swing.JButton();
        soda_DecreaseBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMoney = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtChange = new javax.swing.JTextField();
        purchaseBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        getFreeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Machine");

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel1.setText("Coin-Operated Soda Machine");

        cokeRB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cokeRB.setText("Coke 10.000 VND");
        cokeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeRBActionPerformed(evt);
            }
        });

        pepsiRB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pepsiRB.setText("Pepsi 10.000 VND");
        pepsiRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsiRBActionPerformed(evt);
            }
        });

        sodaRB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sodaRB.setText("Soda 20.000 VND");
        sodaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sodaRBActionPerformed(evt);
            }
        });

        txtCokeQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCokeQuantity.setText("0");
        txtCokeQuantity.setEnabled(false);

        txtPepsiQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPepsiQuantity.setText("0");
        txtPepsiQuantity.setEnabled(false);

        txtSodaQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSodaQuantity.setText("0");
        txtSodaQuantity.setEnabled(false);

        coke_IncreaseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coke_IncreaseBtn.setText("+");
        coke_IncreaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coke_IncreaseBtnActionPerformed(evt);
            }
        });

        coke_DecreaseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coke_DecreaseBtn.setText("-");
        coke_DecreaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coke_DecreaseBtnActionPerformed(evt);
            }
        });

        pepsi_IncreaseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pepsi_IncreaseBtn.setText("+");
        pepsi_IncreaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsi_IncreaseBtnActionPerformed(evt);
            }
        });

        pepsi_DecreaseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pepsi_DecreaseBtn.setText("-");
        pepsi_DecreaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsi_DecreaseBtnActionPerformed(evt);
            }
        });

        soda_IncreaseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        soda_IncreaseBtn.setText("+");
        soda_IncreaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soda_IncreaseBtnActionPerformed(evt);
            }
        });

        soda_DecreaseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        soda_DecreaseBtn.setText("-");
        soda_DecreaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soda_DecreaseBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total:");

        txtTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotalPrice.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("VND");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cokeRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCokeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pepsiRB)
                            .addComponent(sodaRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPepsiQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSodaQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(coke_IncreaseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pepsi_IncreaseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soda_IncreaseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(coke_DecreaseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(pepsi_DecreaseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soda_DecreaseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cokeRB)
                    .addComponent(txtCokeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coke_IncreaseBtn)
                    .addComponent(coke_DecreaseBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pepsiRB)
                    .addComponent(txtPepsiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pepsi_IncreaseBtn)
                    .addComponent(pepsi_DecreaseBtn))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sodaRB)
                    .addComponent(txtSodaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soda_IncreaseBtn)
                    .addComponent(soda_DecreaseBtn))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Insert Money:");

        txtMoney.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Change:");

        txtChange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtChange.setEnabled(false);

        purchaseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchaseBtn.setText("Purchase");
        purchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("VND");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("VND");

        getFreeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getFreeBtn.setText("Get Free");
        getFreeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getFreeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMoney)
                    .addComponent(txtChange, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(192, 192, 192))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(getFreeBtn)
                            .addComponent(purchaseBtn))
                        .addGap(123, 123, 123)
                        .addComponent(clearBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBtn)
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseBtn)
                    .addComponent(clearBtn)
                    .addComponent(cancelBtn))
                .addGap(18, 18, 18)
                .addComponent(getFreeBtn)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // cancel the purchase and receive a refund
        // when click button cancel the purchase, a dialog box will pop up to confirm the purchase and machine will return the money for user.
        //
        //JOptionPane.showConfirmDialog(null, "Do you want to cancel purchasing and receive a refund?", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
        
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // clears all selections
        
        cokeRB.setSelected(false);
        pepsiRB.setSelected(false);
        sodaRB.setSelected(false);
        txtCokeQuantity.setText("0");
        txtPepsiQuantity.setText("0");
        txtSodaQuantity.setText("0");
        txtTotalPrice.setText(" ");
        txtChange.setText(" ");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void cokeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeRBActionPerformed
        // changing radio button to select only one
        
        if (cokeRB.isSelected()) {
            txtPepsiQuantity.setText("0");
            txtSodaQuantity.setText("0");
            txtCokeQuantity.setText("1");
            changeTotalPrice();
            
            pepsiRB.setSelected(false);
            sodaRB.setSelected(false);
                
        } else {
            txtCokeQuantity.setText("0");
        }
    }//GEN-LAST:event_cokeRBActionPerformed

    private void pepsiRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsiRBActionPerformed
        // changing radio button to select only one
        
        if (pepsiRB.isSelected()) {
            txtCokeQuantity.setText("0");
            txtSodaQuantity.setText("0");
            txtPepsiQuantity.setText("1");
            changeTotalPrice();
            
            cokeRB.setSelected(false);
            sodaRB.setSelected(false);
                   
        } else {
            txtPepsiQuantity.setText("0");
        }
    }//GEN-LAST:event_pepsiRBActionPerformed

    private void sodaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sodaRBActionPerformed
        // changing radio button to select only one
        
        if (sodaRB.isSelected()) {
            txtPepsiQuantity.setText("0");
            txtCokeQuantity.setText("0");
            txtSodaQuantity.setText("1");
            changeTotalPrice();
            
            cokeRB.setSelected(false);
            pepsiRB.setSelected(false);
                
        } else {
            txtSodaQuantity.setText("0");
        }
    }//GEN-LAST:event_sodaRBActionPerformed

    private void purchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseBtnActionPerformed
       // proceed to pay when there is enough money
       
        int money = 0;
        int change = 0;
             
        System.out.println("Total win: " + totalWin);
        
        if (totalWin == 40000) {
            freeSoda = false;
        }
        
        // check if the budget is equal to 50000 or not
        boolean checkBudget = checkBudget(totalWin);
       
        int cokeQuantity = Integer.parseInt(txtCokeQuantity.getText());
        int pepsiQuantity = Integer.parseInt(txtPepsiQuantity.getText());
        int sodaQuantity = Integer.parseInt(txtSodaQuantity.getText());
       
        money = Integer.parseInt(txtMoney.getText());
       
        if (cokeRB.isSelected()) {
            change = money - (cokePrice * cokeQuantity);
        } else if (pepsiRB.isSelected()) {
            change = money - (pepsiPrice * pepsiQuantity);
        } else if (sodaRB.isSelected()) {
            change = money - (sodaPrice * sodaQuantity);
        }
        
        checkMoney();
        
        if (change < 0) {
            JOptionPane.showMessageDialog(rootPane, "Sorry, you do not have enough money");
        } else {
            // count the number of times to buy coke
            if (cokeRB.isSelected()) {
                countCoke += 1;
                // Only participate in the program when the number of purchases is equal to 3 and the budget is less than 50000
                System.out.println("coke:"+countCoke);
                if (countCoke == 3 && checkBudget == true) {                
                    freeProduct(freeSoda);
                }
            } else {
                countCoke = 0;
            }
            
            // count the number of times to buy pepsi
            if (pepsiRB.isSelected()) {
                countPepsi += 1;
                System.out.println("pepsi:" + countPepsi);
                if (countPepsi == 3 && checkBudget == true) {                   
                    freeProduct(freeSoda);
                }
            } else {
                countPepsi = 0;
            }
            
            // count the number of times to buy soda
            if (sodaRB.isSelected()) {
                countSoda += 1;
                System.out.println("soda:" + countSoda);
                if (countSoda == 3 && checkBudget == true) {                    
                    freeProduct(freeSoda);
                }
            } else {
                countSoda = 0;
            }
            
            txtChange.setText(Integer.toString(change));
            JOptionPane.showMessageDialog(rootPane, "Thank you for purchasing our products. Your change is: " + change + " VND");
        }
        clearData();
    }//GEN-LAST:event_purchaseBtnActionPerformed

    // <editor-fold defaultstate="collapsed" desc="changes quantity of product">
    
    private void coke_IncreaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coke_IncreaseBtnActionPerformed
        // increase quantity of coke
        if (cokeRB.isSelected()) {
            int cokeQuantity = Integer.parseInt(txtCokeQuantity.getText());
            cokeQuantity += 1;
            txtCokeQuantity.setText(Integer.toString(cokeQuantity));
            changeTotalPrice();
        }       
    }//GEN-LAST:event_coke_IncreaseBtnActionPerformed

    private void coke_DecreaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coke_DecreaseBtnActionPerformed
        // decrease quantity of coke
        if (cokeRB.isSelected()) {
            int cokeQuantity = Integer.parseInt(txtCokeQuantity.getText());
            if (cokeQuantity > 0) {
                cokeQuantity -= 1;
                txtCokeQuantity.setText(Integer.toString(cokeQuantity));
                changeTotalPrice();
            }           
        }
    }//GEN-LAST:event_coke_DecreaseBtnActionPerformed

    private void pepsi_IncreaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsi_IncreaseBtnActionPerformed
        // increase quantity of pepsi
        if (pepsiRB.isSelected()) {
            int pepsiQuantity = Integer.parseInt(txtPepsiQuantity.getText());
            pepsiQuantity += 1;
            txtPepsiQuantity.setText(Integer.toString(pepsiQuantity));
            changeTotalPrice();
        }        
    }//GEN-LAST:event_pepsi_IncreaseBtnActionPerformed

    private void pepsi_DecreaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsi_DecreaseBtnActionPerformed
        // decrease quantity of pepsi
        if (pepsiRB.isSelected()) {
            int pepsiQuantity = Integer.parseInt(txtPepsiQuantity.getText());
            if (pepsiQuantity > 0) {
                pepsiQuantity -= 1;
                txtPepsiQuantity.setText(Integer.toString(pepsiQuantity));
                changeTotalPrice();
            }           
        }       
    }//GEN-LAST:event_pepsi_DecreaseBtnActionPerformed

    private void soda_IncreaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soda_IncreaseBtnActionPerformed
        // increase quantity of soda
        if (sodaRB.isSelected()) {
            int sodaQuantity = Integer.parseInt(txtSodaQuantity.getText());
            sodaQuantity += 1;
            txtSodaQuantity.setText(Integer.toString(sodaQuantity));
            changeTotalPrice();
        }       
    }//GEN-LAST:event_soda_IncreaseBtnActionPerformed

    private void soda_DecreaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soda_DecreaseBtnActionPerformed
        // decrease quantity of soda
        if (sodaRB.isSelected()) {
            int sodaQuantity = Integer.parseInt(txtSodaQuantity.getText());
            if (sodaQuantity > 0) {
                sodaQuantity -= 1;
                txtSodaQuantity.setText(Integer.toString(sodaQuantity));
                changeTotalPrice();
            }            
        }     
    }//GEN-LAST:event_soda_DecreaseBtnActionPerformed

    private void getFreeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getFreeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getFreeBtnActionPerformed
    
    // </editor-fold>
    
    // change total price when change quantity of product   
    public void changeTotalPrice() {
        int cokeQuantity = Integer.parseInt(txtCokeQuantity.getText());
        int pepsiQuantity = Integer.parseInt(txtPepsiQuantity.getText());
        int sodaQuantity = Integer.parseInt(txtSodaQuantity.getText());
        
        totalPrice = cokePrice * cokeQuantity + pepsiPrice * pepsiQuantity + sodaPrice * sodaQuantity;
        txtTotalPrice.setText(Integer.toString(totalPrice));
    }
    
    // check the face value of the money put in   
    public void checkMoney() {
        
        // if i have more time, i will research how the vending machine checks the value of money put in; using AI, Machine Learning techniques to compare money put in
        // with real money and value of it.
        
        int money = 0;
        money = Integer.parseInt(txtMoney.getText());
        if (money != 10000 && money != 20000 && money != 50000 && money != 100000 && money != 200000) {
            JOptionPane.showMessageDialog(rootPane, "The amount of money you input is not valid. Please try again.");
        }
    }
    
    // clear data after purchase
    public void clearData() {
        cokeRB.setSelected(false);
        pepsiRB.setSelected(false);
        sodaRB.setSelected(false);
        txtCokeQuantity.setText("0");
        txtPepsiQuantity.setText("0");
        txtSodaQuantity.setText("0");
        txtTotalPrice.setText(" ");
        txtChange.setText(" ");
    }
    
    // probability 10% to receive a free product
    public boolean probability() {
        Random rand = new Random();
        boolean freeProduct = rand.nextInt(1) == 0;
        return freeProduct;
    }
    
    // win a prize
    public void freeProduct (boolean freeSoda) {
        boolean chanceForFree = probability();
        if (chanceForFree == true) {
            if (freeSoda == true) {
                JOptionPane.showMessageDialog(rootPane, "You are very lucky, you get a free product 😁. Buy it for 0 VND");
                // At this time, the product price will be 0 VND
                cokePrice = 0;
                pepsiPrice = 0;
                sodaPrice = 0;
                cokeRB.setText("Coke 0 VND");
                pepsiRB.setText("Pepsi 0 VND");
                sodaRB.setText("Soda 0 VND");
                if (cokeRB.isSelected()) {
                    totalWin += 10000;
                } 
                if (pepsiRB.isSelected()) {
                    totalWin += 10000;
                }
                if (sodaRB.isSelected()) {
                    totalWin += 20000;
                }
                countCoke = -1; // -1 is because after buying for 0 VND, the count will increase 1
                countPepsi = -1;
                countSoda = -1;
            } else {
                JOptionPane.showMessageDialog(rootPane, "You are very lucky, you get a free product 😁. Buy it for 0 VND except Soda because it is beyond our budget");
                sodaRB.setVisible(false);
                txtSodaQuantity.setVisible(false);
                soda_IncreaseBtn.setVisible(false);
                soda_DecreaseBtn.setVisible(false);
                cokePrice = 0;
                pepsiPrice = 0;
                cokeRB.setText("Coke 0 VND");
                pepsiRB.setText("Pepsi 0 VND");
                if (cokeRB.isSelected()) {
                    totalWin += 10000;
                } 
                if (pepsiRB.isSelected()) {
                    totalWin += 10000;
                }
            }
            // check if the user has received the free product
            //getFree = true;
            getFreeBtn.setVisible(true);
        }
    }
    
    // Reinstall the device after winning
    public void reInstallAfterWin () {
        cokePrice = 10000;
        pepsiPrice = 10000;
        sodaPrice = 20000;
        cokeRB.setText("Coke 10.000 VND");
        pepsiRB.setText("Pepsi 10.000 VND");
        sodaRB.setText("Soda 10.000 VND");
    }
    
    // limited budget is 50000 VND a day
    public boolean checkBudget(int totalWin) {
        int budget = 50000;
        if (budget == totalWin) {
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coin_OperatedMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coin_OperatedMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coin_OperatedMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coin_OperatedMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coin_OperatedMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JRadioButton cokeRB;
    private javax.swing.JButton coke_DecreaseBtn;
    private javax.swing.JButton coke_IncreaseBtn;
    private javax.swing.JButton getFreeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton pepsiRB;
    private javax.swing.JButton pepsi_DecreaseBtn;
    private javax.swing.JButton pepsi_IncreaseBtn;
    private javax.swing.JButton purchaseBtn;
    private javax.swing.JRadioButton sodaRB;
    private javax.swing.JButton soda_DecreaseBtn;
    private javax.swing.JButton soda_IncreaseBtn;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtCokeQuantity;
    private javax.swing.JTextField txtMoney;
    private javax.swing.JTextField txtPepsiQuantity;
    private javax.swing.JTextField txtSodaQuantity;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
